[package]
name = "wammu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = [ "cargo" ] }
indicatif = "0.17.3"
libc = "0.2.139"
log = "0.4.17"

